import React from 'react';
import { View, ViewStyle } from 'react-native';
import { useTheme } from '../lib/theme';
import {
  Home,
  MessageCircle,
  Search,
  User,
  Settings,
  Bell,
  Heart,
  Share2,
  Send,
  Plus,
  Camera,
  Image as ImageIcon,
  MapPin,
  Calendar,
  Clock,
  MoreHorizontal,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  Check,
  X,
  Menu,
  LogOut,
  Edit3,
  Trash2,
  Download,
  Upload,
  Paperclip,
  Mic,
  Phone,
  Video,
  Users,
  UserPlus,
  UserMinus,
  Shield,
  Crown,
  Star,
  ThumbsUp,
  MessageSquare,
  Repeat,
  Bookmark,
  Hash,
  AtSign,
  Mail,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  SearchIcon,
  Filter,
  SortAsc,
  Globe,
  BookOpen,
  GraduationCap,
  Briefcase,
  Award,
  Zap,
  Flame,
  TrendingUp,
  BarChart2,
  PieChart,
  Activity,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  Sun,
  Moon,
  Monitor,
  Smartphone,
  Laptop,
  Tablet,
  Printer,
  Save,
  Folder,
  FileText,
  File,
  Copy,
  Scissors,
  Clipboard,
  Layers,
  Layout,
  Grid,
  List,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Type,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Link,
  ExternalLink,
  Maximize,
  Minimize,
  Maximize2,
  Minimize2,
  Move,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Volume2,
  Volume1,
  VolumeX,
  MicOff,
  VideoOff,
  PhoneOff,
  PlusCircle,
  MinusCircle,
  CheckCircle,
  XCircle,
  HelpCircle,
  Info,
  AlertTriangle,
  AlertCircle,
  ShieldAlert,
  Flag,
  FlagOff,
  Pin,
  PinOff,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftCircle,
  ArrowRightCircle,
  ArrowUpLeft,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowDownRight,
  CornerUpLeft,
  CornerUpRight,
  CornerDownLeft,
  CornerDownRight,
  ChevronsUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  Navigation,
  Compass,
  Map,
  Locate,
  LocateFixed,
  LocateOff,
  Target,
  Crosshair,
  Aperture,
  Camera as CameraIcon,
  Image as LucideImage,
  Video as LucideVideo,
  Film,
  Music,
  Headphones,
  Radio,
  Tv,
  Cast,
  Airplay,
  Bluetooth,
  Wifi as LucideWifi,
  Signal,
  SignalHigh,
  SignalMedium,
  SignalLow,
  Battery as LucideBattery,
  Power,
  PowerOff,
  ToggleLeft,
  ToggleRight,
  Sliders,
  SlidersHorizontal,
  Settings2,
  Wrench,
  Hammer,
  Brush,
  PenTool,
  Pencil,
  Eraser,
  Scissors as LucideScissors,
  Ruler,
  Triangle,
  Circle,
  Square as LucideSquare,
  Hexagon,
  Octagon,
  Pentagon,
  Star as LucideStar,
  Heart as LucideHeart,
  ThumbsDown,
  Smile,
  Frown,
  Meh,
  Laugh,
  Annoyed,
  Ghost,
  Skull,
  Crown as LucideCrown,
  Gem,
  Gift,
  Package,
  Box,
  Truck,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Banknote,
  Wallet,
  PiggyBank,
  Receipt,
  Ticket,
  Tag,
  Tags,
  QrCode,
  Barcode,
  ScanLine,
  Scan,
  Fingerprint,
  Key,
  Lock as LucideLock,
  Unlock as LucideUnlock,
  Eye as LucideEye,
  EyeOff as LucideEyeOff,
  Glasses,
  Accessibility,
  PersonStanding,
  Baby,
  Flower,
  Leaf,
  TreePine,
  TreeDeciduous,
  Mountain,
  Cloud,
  CloudRain,
  CloudLightning,
  CloudSnow,
  CloudSun,
  CloudMoon,
  SunDim,
  Sunrise,
  Sunset,
  Moon as LucideMoon,
  Thermometer,
  Wind,
  Droplets,
  Umbrella,
  Snowflake,
  Flame as LucideFlame,
  Sparkles,
  Zap as LucideZap,
  ZapOff,
  Plug,
  PlugZap,
  BatteryWarning,
  Trash,
  Trash2 as LucideTrash2,
  Recycle,
  Scissors as Scissors2,
  Flower2,
  Shell,
  Anchor,
  Ship,
  Sailboat,
  Fish,
  Bird,
  Cat,
  Dog,
  Rabbit,
  Turtle,
  Snail,
  Bug,
  Feather,
  Plane,
  Rocket,
  Lasso,
  Sword,
  Swords,
  Shield as LucideShield,
  ShieldCheck,
  ShieldX,
  ShieldQuestion,
  ShieldOff,
  Badge,
  BadgeCheck,
  BadgeAlert,
  BadgeX,
  Medal,
  Trophy,
  Crown as Crown2,
  Gem as Gem2,
  Diamond,
  Club,
  Spade,
  Heart as Heart2,
  HeartCrack,
  HeartHandshake,
  HeartPulse,
  Activity as LucideActivity,
  Brain,
  BrainCircuit,
  Cpu,
  Database,
  HardDrive,
  Server,
  Network,
  Wifi as Wifi2,
  EthernetPort,
  Usb,
  HdmiPort,
  Cable,
  Monitor as LucideMonitor,
  MonitorSmartphone,
  Smartphone as LucideSmartphone,
  Tablet as LucideTablet,
  Laptop as LucideLaptop,
  Keyboard,
  Mouse,
  MousePointer,
  MousePointer2,
  MousePointerClick,
  Joystick,
  Gamepad,
  Gamepad2,
  Dices,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Puzzle,
  Binary,
  Code,
  Code2,
  Terminal,
  TerminalSquare,
  CurlyBraces,
  Parentheses,
  Brackets,
  Quote,
  Asterisk,
  Hash as LucideHash,
  AtSign as LucideAtSign,
  Ampersand,
  Percent,
  DollarSign,
  Euro,
  PoundSterling,
  JapaneseYen,
  RussianRuble,
  IndianRupee,
  Bitcoin,
  GitCommit,
  GitMerge,
  GitPullRequest,
  GitPullRequestClosed,
  GitPullRequestDraft,
  Kanban,
  KanbanSquare,
  FileCode,
  FileJson,
  FileType,
  FileType2,
  FileSpreadsheet,
  FileBarChart,
  FilePieChart,
  FileLineChart,
  FileCog,
  FileKey,
  FileLock,
  FileCheck,
  FileX,
  FileQuestion,
  FileWarning,
  FilePlus,
  FileMinus,
  Folder as LucideFolder,
  FolderOpen,
  FolderPlus,
  FolderMinus,
  FolderX,
  FolderCheck,
  FolderCog,
  FolderLock,
  FolderHeart,
  FolderArchive,
  FolderGit,
  FolderGit2,
  Folders,
  HardDrive as LucideHardDrive,
  Database as LucideDatabase,
  Server as LucideServer,
  ServerOff,
  ServerCrash,
  Layers as LucideLayers,
  Layers2,
  Layout as LucideLayout,
  LayoutGrid,
  LayoutList,
  LayoutTemplate,
  LayoutDashboard,
  Table,
  Table2,
  Columns,
  Rows,
  GripVertical,
  GripHorizontal,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  PanelLeftClose,
  PanelRightClose,
  PanelTopClose,
  PanelBottomClose,
  Sidebar,
  SidebarOpen,
  SidebarClose,
  Menu as LucideMenu,
  Command,
  Bot,
  BotMessageSquare,
  Sparkles as LucideSparkles,
  Wand,
  Wand2,
  Paintbrush,
  Palette,
  GlassWater,
  CupSoda,
  Coffee,
  Beer,
  Wine,
  Pizza,
  Hamburger,
  Sandwich,
  Soup,
  IceCream,
  Cookie,
  Candy,
  Donut,
  Croissant,
  Cherry,
  Grape,
  Apple,
  Citrus,
  Carrot,
  Beef,
  FishSymbol,
  Egg,
  Milk,
  Coffee as Coffee2,
  CupSoda as CupSoda2,
  Utensils,
  UtensilsCrossed,
  ForkKnife,
  Spade as Spade2,
  Anchor as Anchor2,
  LifeBuoy,
  Compass as LucideCompass,
  Globe2,
  Globe as LucideGlobe,
  Map as LucideMap,
  MapPin as LucideMapPin,
  Navigation as LucideNavigation,
  Navigation2,
  Navigation2Off,
  Locate as LucideLocate,
  LocateOff as LucideLocateOff,
  MapPinned,
  Pin as LucidePin,
  PinOff as LucidePinOff,
  Home as LucideHome,
  Building,
  Building2,
  Castle,
  Church,
  School,
  School2,
  Hotel,
  Hospital,
  Warehouse,
  Factory,
  Store,
  ShoppingBag as ShoppingBag2,
  ShoppingCart as ShoppingCart2,
  Gift as Gift2,
  Package as Package2,
  PackageOpen,
  PackageCheck,
  PackageX,
  PackageSearch,
  Container,
  Truck as LucideTruck,
  Train,
  Bus,
  Car,
  CarFront,
  ParkingCircle,
  ParkingSquare,
  Fuel,
  Gauge,
  CircleParking,
  CircleParkingOff,
  Tent,
  TentTree,
  Trees,
  TreePine as TreePine2,
  TreeDeciduous as TreeDeciduous2,
  Palmtree,
  Flower as Flower3,
  Clover,
  Sprout,
  Vegan,
  Wheat,
  WheatOff,
  Cigarette,
  CigaretteOff,
  WineOff,
  BeerOff,
  MilkOff,
  EggOff,
  NutOff,
  FishOff,
  BeefOff,
  Wheat as Wheat2,
  Cookie as Cookie2,
  Candy as Candy2,
  CandyOff,
  IceCream2,
  IceCreamCone,
  Popsicle,
  Lollipop,
  Croissant as Croissant2,
  Sandwich as Sandwich2,
  Soup as Soup2,
  Salad,
  Utensils as Utensils2,
  UtensilsCrossed as UtensilsCrossed2,
  ForkKnife as ForkKnife2,
  Coffee as Coffee3,
  CupSoda as CupSoda3,
  GlassWater as GlassWater2,
  Beer as Beer2,
  Wine as Wine2,
  Pizza as Pizza2,
  Hamburger as Hamburger2,
  Carrot as Carrot2,
  Apple as Apple2,
  Banana,
  Cherry as Cherry2,
  Citrus as Citrus2,
  Grape as Grape2,
  Carrot as Carrot3,
  Egg as Egg2,
  Milk as Milk2,
  Nut,
  Fish as Fish2,
  Beef as Beef2,
  Drumstick,
  Popcorn,
  Beef as Beef3,
  Fish as Fish3,
  Anchor as Anchor3,
  Bike,
  CircleParking as CircleParking2,
  CircleParkingOff as CircleParkingOff2,
  Fuel as Fuel2,
  Gauge as Gauge2,
  NavigationOff,
  Plane as Plane2,
  PlaneTakeoff,
  PlaneLanding,
  Rocket as Rocket2,
  Sailboat as Sailboat2,
  Ship as Ship2,
  TrainFront,
  TrainTrack,
  TramFront,
  Truck as Truck2,
  BusFront,
  Bus as Bus2,
  Car as Car2,
  CarTaxiFront,
  CarFront as CarFront2,
} from 'lucide-react-native';

export type IconName = 
  | 'home' | 'message-circle' | 'search' | 'user' | 'settings' | 'bell' | 'heart' | 'share-2'
  | 'send' | 'plus' | 'camera' | 'image' | 'map-pin' | 'calendar' | 'clock' | 'more-horizontal'
  | 'more-vertical' | 'chevron-left' | 'chevron-right' | 'check' | 'x' | 'menu' | 'log-out'
  | 'edit-3' | 'trash-2' | 'download' | 'upload' | 'paperclip' | 'mic' | 'phone' | 'video'
  | 'users' | 'user-plus' | 'user-minus' | 'shield' | 'crown' | 'star' | 'thumbs-up'
  | 'message-square' | 'repeat' | 'bookmark' | 'hash' | 'at-sign' | 'mail' | 'lock' | 'unlock'
  | 'eye' | 'eye-off' | 'filter' | 'sort-asc' | 'globe' | 'book-open' | 'graduation-cap'
  | 'briefcase' | 'award' | 'zap' | 'flame' | 'trending-up' | 'bar-chart-2' | 'pie-chart'
  | 'activity' | 'wifi' | 'wifi-off' | 'sun' | 'moon' | 'smartphone' | 'laptop' | 'tablet'
  | 'save' | 'folder' | 'file-text' | 'file' | 'copy' | 'clipboard' | 'layers' | 'layout'
  | 'grid' | 'list' | 'type' | 'bold' | 'italic' | 'link' | 'external-link' | 'maximize'
  | 'minimize' | 'refresh-cw' | 'play' | 'pause' | 'skip-back' | 'skip-forward' | 'volume-2'
  | 'volume-x' | 'plus-circle' | 'minus-circle' | 'check-circle' | 'x-circle' | 'help-circle'
  | 'info' | 'alert-triangle' | 'alert-circle' | 'arrow-up' | 'arrow-down' | 'arrow-left'
  | 'arrow-right' | 'navigation' | 'compass' | 'map' | 'target' | 'crosshair' | 'film'
  | 'music' | 'headphones' | 'bluetooth' | 'power' | 'toggle-right' | 'sliders'
  | 'pen-tool' | 'pencil' | 'ruler' | 'circle' | 'hexagon' | 'diamond' | 'smile' | 'frown'
  | 'gift' | 'package' | 'shopping-cart' | 'credit-card' | 'wallet' | 'qr-code' | 'fingerprint'
  | 'key' | 'accessibility' | 'cloud' | 'cloud-rain' | 'sunrise' | 'thermometer' | 'wind'
  | 'droplets' | 'umbrella' | 'snowflake' | 'sparkles' | 'plane' | 'rocket' | 'anchor'
  | 'trophy' | 'medal' | 'cpu' | 'database' | 'server' | 'hard-drive' | 'keyboard'
  | 'mouse-pointer' | 'gamepad' | 'code' | 'terminal' | 'command' | 'bot' | 'wand-2' | 'palette' | 'coffee'
  | 'pizza' | 'beer' | 'car' | 'train' | 'bus' | 'hotel' | 'hospital' | 'store' | 'school'
  | 'church' | 'castle' | 'building' | 'warehouse' | 'factory' | 'trees' | 'flower' | 'leaf'
  | 'mountain' | 'parking-circle' | 'fuel' | 'gauge' | 'bike' | 'plane-takeoff' | 'plane-landing'
  | 'tram-front' | 'train-front' | 'train-track' | 'car-taxi-front';

interface IconProps {
  name: IconName;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: ViewStyle;
}

const iconMap: Record<IconName, React.ComponentType<any>> = {
  'home': Home,
  'message-circle': MessageCircle,
  'search': Search,
  'user': User,
  'settings': Settings,
  'bell': Bell,
  'heart': Heart,
  'share-2': Share2,
  'send': Send,
  'plus': Plus,
  'camera': Camera,
  'image': ImageIcon,
  'map-pin': MapPin,
  'calendar': Calendar,
  'clock': Clock,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'check': Check,
  'x': X,
  'menu': Menu,
  'log-out': LogOut,
  'edit-3': Edit3,
  'trash-2': Trash2,
  'download': Download,
  'upload': Upload,
  'paperclip': Paperclip,
  'mic': Mic,
  'phone': Phone,
  'video': Video,
  'users': Users,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'shield': Shield,
  'crown': Crown,
  'star': Star,
  'thumbs-up': ThumbsUp,
  'message-square': MessageSquare,
  'repeat': Repeat,
  'bookmark': Bookmark,
  'hash': Hash,
  'at-sign': AtSign,
  'mail': Mail,
  'lock': Lock,
  'unlock': Unlock,
  'eye': Eye,
  'eye-off': EyeOff,
  'filter': Filter,
  'sort-asc': SortAsc,
  'globe': Globe,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  'briefcase': Briefcase,
  'award': Award,
  'zap': Zap,
  'flame': Flame,
  'trending-up': TrendingUp,
  'bar-chart-2': BarChart2,
  'pie-chart': PieChart,
  'activity': Activity,
  'wifi': Wifi,
  'wifi-off': WifiOff,
  'sun': Sun,
  'moon': Moon,
  'smartphone': Smartphone,
  'laptop': Laptop,
  'tablet': Tablet,
  'save': Save,
  'folder': Folder,
  'file-text': FileText,
  'file': File,
  'copy': Copy,
  'clipboard': Clipboard,
  'layers': Layers,
  'layout': Layout,
  'grid': Grid,
  'list': List,
  'type': Type,
  'bold': Bold,
  'italic': Italic,
  'link': Link,
  'external-link': ExternalLink,
  'maximize': Maximize,
  'minimize': Minimize,
  'refresh-cw': RefreshCw,
  'play': Play,
  'pause': Pause,
  'skip-back': SkipBack,
  'skip-forward': SkipForward,
  'volume-2': Volume2,
  'volume-x': VolumeX,
  'plus-circle': PlusCircle,
  'minus-circle': MinusCircle,
  'check-circle': CheckCircle,
  'x-circle': XCircle,
  'help-circle': HelpCircle,
  'info': Info,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'navigation': Navigation,
  'compass': Compass,
  'map': Map,
  'target': Target,
  'crosshair': Crosshair,
  'film': Film,
  'music': Music,
  'headphones': Headphones,
  'bluetooth': Bluetooth,
  'power': Power,
  'toggle-right': ToggleRight,
  'sliders': Sliders,
  'pen-tool': PenTool,
  'pencil': Pencil,
  'ruler': Ruler,
  'circle': Circle,
  'hexagon': Hexagon,
  'diamond': Diamond,
  'smile': Smile,
  'frown': Frown,
  'gift': Gift,
  'package': Package,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  'wallet': Wallet,
  'qr-code': QrCode,
  'fingerprint': Fingerprint,
  'key': Key,
  'accessibility': Accessibility,
  'cloud': Cloud,
  'cloud-rain': CloudRain,
  'sunrise': Sunrise,
  'thermometer': Thermometer,
  'wind': Wind,
  'droplets': Droplets,
  'umbrella': Umbrella,
  'snowflake': Snowflake,
  'sparkles': Sparkles,
  'plane': Plane,
  'rocket': Rocket,
  'anchor': Anchor,
  'trophy': Trophy,
  'medal': Medal,
  'cpu': Cpu,
  'database': Database,
  'server': Server,
  'hard-drive': HardDrive,
  'keyboard': Keyboard,
  'mouse-pointer': MousePointer,
  'gamepad': Gamepad,
  'code': Code,
  'terminal': Terminal,
  'command': Command,
  'bot': Bot,
  'wand-2': Wand2,
  'palette': Palette,
  'coffee': Coffee,
  'pizza': Pizza,
  'beer': Beer,
  'car': Car,
  'train': Train,
  'bus': Bus,
  'hotel': Hotel,
  'hospital': Hospital,
  'store': Store,
  'school': School,
  'church': Church,
  'castle': Castle,
  'building': Building,
  'warehouse': Warehouse,
  'factory': Factory,
  'trees': Trees,
  'flower': Flower,
  'leaf': Leaf,
  'mountain': Mountain,
  'parking-circle': ParkingCircle,
  'fuel': Fuel,
  'gauge': Gauge,
  'bike': Bike,
  'plane-takeoff': PlaneTakeoff,
  'plane-landing': PlaneLanding,
  'tram-front': TramFront,
  'train-front': TrainFront,
  'train-track': TrainTrack,
  'car-taxi-front': CarTaxiFront,
};

export function Icon({ name, size = 24, color, strokeWidth = 2, style }: IconProps) {
  const { colors } = useTheme();
  const IconComponent = iconMap[name];
  
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }

  return (
    <View style={style}>
      <IconComponent
        size={size}
        color={color || colors.text}
        strokeWidth={strokeWidth}
      />
    </View>
  );
}

export default Icon;

// Re-export all Lucide icons for direct usage
export {
  Home,
  MessageCircle,
  Search,
  User,
  Settings,
  Bell,
  Heart,
  Share2,
  Send,
  Plus,
  Camera,
  MapPin,
  Calendar,
  Clock,
  MoreHorizontal,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  Check,
  X,
  Menu,
  LogOut,
  Edit3,
  Trash2,
  Download,
  Upload,
  Paperclip,
  Mic,
  Phone,
  Video,
  Users,
  UserPlus,
  UserMinus,
  Shield,
  Crown,
  Star,
  ThumbsUp,
  MessageSquare,
  Repeat,
  Bookmark,
  Hash,
  AtSign,
  Mail,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Filter,
  SortAsc,
  Globe,
  BookOpen,
  GraduationCap,
  Briefcase,
  Award,
  Zap,
  Flame,
  TrendingUp,
  BarChart2,
  PieChart,
  Activity,
  Wifi,
  WifiOff,
  Sun,
  Moon,
  Smartphone,
  Laptop,
  Tablet,
  Save,
  Folder,
  FileText,
  File,
  Copy,
  Clipboard,
  Layers,
  Layout,
  Grid,
  List,
  Type,
  Bold,
  Italic,
  Link,
  ExternalLink,
  Maximize,
  Minimize,
  RefreshCw,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Volume2,
  VolumeX,
  PlusCircle,
  MinusCircle,
  CheckCircle,
  XCircle,
  HelpCircle,
  Info,
  AlertTriangle,
  AlertCircle,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Navigation,
  Compass,
  Map,
  Target,
  Crosshair,
  Film,
  Music,
  Headphones,
  Bluetooth,
  Power,
  ToggleRight,
  Sliders,
  PenTool,
  Pencil,
  Ruler,
  Circle,
  Hexagon,
  Diamond,
  Smile,
  Frown,
  Gift,
  Package,
  ShoppingCart,
  CreditCard,
  Wallet,
  QrCode,
  Fingerprint,
  Key,
  Accessibility,
  Cloud,
  CloudRain,
  Sunrise,
  Thermometer,
  Wind,
  Droplets,
  Umbrella,
  Snowflake,
  Sparkles,
  Plane,
  Rocket,
  Anchor,
  Trophy,
  Medal,
  Cpu,
  Database,
  Server,
  HardDrive,
  Keyboard,
  MousePointer,
  Gamepad,
  Code,
  Terminal,
  Command,
  Bot,
  Wand2,
  Palette,
  Coffee,
  Pizza,
  Beer,
  Car,
  Train,
  Bus,
  Hotel,
  Hospital,
  Store,
  School,
  Church,
  Castle,
  Building,
  Warehouse,
  Factory,
  Trees,
  Flower,
  Leaf,
  Mountain,
  ParkingCircle,
  Fuel,
  Gauge,
  Bike,
  PlaneTakeoff,
  PlaneLanding,
  TramFront,
  TrainFront,
  TrainTrack,
  CarTaxiFront,
};
